version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "9:00"
      timezone: "UTC"
    reviewers: [meltano/engineering]
    labels: [deps]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers: [meltano/engineering]
    labels: [deps]
