[tool.poetry]
name = "cron-ext"
version = "0.0.1"
description = "`cron-ext` is a Meltano utility extension that provides basic job scheduling via CRON."
authors = ["Meltano <hello@meltano.com>"]
license = "MIT"

[tool.poetry.dependencies]
cached-property = "^1" # Remove after Python 3.7 support is dropped
click = "^8.1.3"
meltano-edk = {git = "https://github.com/meltano/edk.git", rev = "main"}
pydantic = "^1.9.0"
python = ">=3.7,<3.11"
PyYAML = "^6.0.0"
structlog = "^21.2.0"
typer = "^0.6.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^3.9.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

packages = [
    { include = "cron_ext" }
]

[tool.poetry.scripts]
cron = 'cron_ext.main:app'
