name: Test

on:
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch:
    inputs: {}

env:
  FORCE_COLOR: "1"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - name: Run Pytest
        run: |
          docker compose -f tests/compose.yml build --build-arg PYTHON_VERSION="${{ matrix.python-version }}"
          docker compose -f tests/compose.yml run pytest
