name: Test

on:
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch:
    inputs: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Run Pytest
        run: |
          docker-compose -f tests/compose.yml build --build-arg PYTHON_VERSION="${{ matrix.python-version }}"
          docker-compose -f tests/compose.yml run pytest
